/* COOKT photography world. Editable content is owned by brand.json. */
'use strict';
const photoEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photoRecord=()=>window.COOKT.photography;
const photoProduct=id=>window.COOKT.products.find(p=>p.id===id);
const pwe=photoEscape;
const photoTagline=()=>pwe(window.COOKT.tagline).toLowerCase().replace(/^a /,'A ');
function pwImage(id,cls='',caption=false){const i=photoRecord().images.find(i=>i.id===id);return `<figure class="pw-photo ${cls}"><img src="${pwe(i.image)}" alt="${pwe(i.alt)}" loading="eager">${caption?`<figcaption>${pwe(i.caption)}</figcaption>`:''}</figure>`;}
function pwRules(rows){return `<div class="pw-rules">${rows.map((x,i)=>`<div><span class="pw-rule-n">${String(i+1).padStart(2,'0')}</span><h3>${pwe(x.title)}</h3><p>${pwe(x.text)}</p></div>`).join('')}</div>`;}
function pwHead(kicker,title,text=''){return `<div class="pw-heading"><span class="pw-kicker">${pwe(kicker)}</span><h2>${pwe(title)}</h2>${text?`<p>${pwe(text)}</p>`:''}</div>`;}
function pwSlide(id,label,body,cls=''){return `<section class="pw-slide ${cls}" id="photo-${id}" data-photo-section="${id}"><header class="pw-running"><span>COOKT / Photography</span><span>${pwe(label)}</span></header>${body}<footer class="pw-folio"><span>Photography direction · In review</span><span class="pw-page-number"></span></footer></section>`;}
function pwReferenceSlide(kind){const refs=window.COOKT_PHOTO_REFS;if(!refs)return '';const ids=kind==='light'?['ref-006','ref-036','ref-217','ref-039']:['ref-015','ref-151','ref-218','ref-007'];const labels=kind==='light'?['Light draws the grid.','Glaze, glass and sauce catch it.','Strong color stays architectural.','A gesture activates the table.']:['Let someone eat.','A chair implies a person.','Keep the plate at real scale.','Compose for connection.'];return pwSlide('refs-'+kind,'Selected visual references',pwHead('From the saved boards',kind==='light'?'Light, color, appetite.':'A meal already in progress.')+`<div class="pw-reference-grid">${ids.map((id,n)=>{const r=refs.find(r=>r.id===id);return `<figure><a href="${pwe(r.pin)}"><img src="${pwe(r.image)}" alt="${pwe(r.alt)}"></a><figcaption><strong>${labels[n]}</strong><span>${r.board} / ${id.replace('ref-','R')}</span></figcaption></figure>`;}).join('')}</div><p class="pw-note">Curated from the saved reference boards. Visual references, not COOKT assets. Source links are attached to each image.</p>`,'pw-ref-slide');}
function renderPhotographyGuide(view='pov'){
const P=photoRecord();let s=[];
s.push(pwSlide('pov','The photo world',`<div class="pw-cover-title"><img src="assets/logo.png" alt="COOKT"><h1>Photography</h1><p>${pwe(P.pov)}</p></div><div class="pw-cover-images">${pwImage('blue-table')}${pwImage('shared-table')}${pwImage('place-setting')}</div><p class="pw-cover-deck">${pwe(P.intro)}</p>`,'pw-cover'));
s.push(pwReferenceSlide('light'));s.push(pwReferenceSlide('life'));
s.push(pwSlide('collections','One world / three roles',pwHead('The system','Three ways into the meal.')+`<div class="pw-collection-grid">${P.collections.map((c,n)=>`<article>${pwImage(c.image)}<span class="pw-kicker">0${n+1}</span><h3>${pwe(c.title)}</h3><p>${pwe(c.purpose)}</p><small>${pwe(c.use)}</small></article>`).join('')}</div>`));
s.push(pwSlide('light','01 / The graphic table',`<div class="pw-feature-grid"><div>${pwHead('The signature','Sculpted light.')}<p class="pw-large">A clear source.<br>A readable shadow.<br>A meal with presence.</p>${pwRules(P.light)}</div>${pwImage('blue-table')}</div>`,'pw-blue-feature'));
s.push(pwSlide('graphic','01 / The graphic table',`<div class="pw-ad-example">${pwImage('yellow-overhead')}<div class="pw-on-photo"><span class="pw-kicker">A graphic composition</span><h2>Let the<br>meal lead.</h2><p>A complete dish. A strong field.<br>Space ready for the message.</p></div></div><div class="pw-caption-row"><p>Overhead makes the ceramic and the whole meal easy to read. Keep the visual rhythm simple enough to work at thumbnail size.</p><span>Use / campaign, homepage, paid social</span></div>`,'pw-full'));
s.push(pwSlide('lifestyle','02 / Life at the table',`<div class="pw-life-grid">${pwImage('shared-table')}<div>${pwHead('A shared table','Gestures give the picture a reason.')}<p>${pwe(P.lifestyle[0].text)}</p><small>Use / organic social, community, editorial</small></div></div>`,'pw-life'));
s.push(pwSlide('evening','02 / Life at the table',`<div class="pw-evening-grid">${pwImage('place-setting')}<div>${pwHead('Implied presence','Set a place.')}<p class="pw-large">${pwe(P.lifestyle[2].text)}</p><div class="pw-evening-swatches"><i style="background:#103e2c"></i><i style="background:#b65a33"></i><i style="background:#e8dec9"></i></div><p>${pwe(P.lifestyle[1].text)}</p><small>Use / CRM, editorial, occasion-led social</small></div></div>`,'pw-evening'));
s.push(pwSlide('food','03 / Close appetite',pwHead('Food styling','Make the texture tangible.')+pwImage('detail','pw-detail')+pwRules(P.food),'pw-food'));
s.push(pwSlide('color','Color / the decision',pwHead('Build outward from the dish','Anchor. Secondary. Tertiary.',P.colorIntro)+pwRules(P.colorRules)+`<div class="pw-palette-grid">${P.colorSets.map(c=>`<article>${pwImage(c.image)}<div class="pw-swatches">${c.colors.map((color,n)=>`<span><i style="background:${color}"></i>${pwe(c.labels[n])}</span>`).join('')}</div><h3>${pwe(c.title)}</h3><p>${pwe(c.text)}</p></article>`).join('')}</div>`,'pw-color'));
s.push(pwSlide('sets','Set design / material vocabulary',pwHead('Make the set do useful work','Tile. Wood. Cloth. Glass.')+`<div class="pw-material-grid">${pwImage('blue-table')}${pwImage('shared-table')}${pwImage('place-setting')}</div>`+pwRules(P.setRules),'pw-sets'));
s.push(pwSlide('plates','Dish and packaging continuity',pwHead('Keep the product recognizable','One dish. A consistent ceramic.','Retain the curated plate language and the established package photography angle. The wider photographic world can change its distance, surface and occasion.')+`<div class="pw-plate-grid">${P.plates.map(x=>{const p=photoProduct(x.product);return `<article><img src="${pwe(p.image)}" alt="${pwe(p.name)}"><h3>${pwe(p.name)}</h3><p>${pwe(x.name)}</p><small>${pwe(x.status)} / ${pwe(x.note)}</small></article>`;}).join('')}</div><div class="pw-angle-row">${P.angles.map(x=>`<div><h3>${pwe(x.title)}</h3><p>${pwe(x.text)}</p></div>`).join('')}</div>`,'pw-plates'));
s.push(pwSlide('choose','Choose the photograph',pwHead('Start with the job','What does this image need to do?')+`<div class="pw-decision-table"><div class="pw-table-head"><span>Job / touchpoint</span><span>Photograph</span><span>Why / composition</span></div>${P.decisions.map(d=>{const p=d.imageProduct&&photoProduct(d.imageProduct);const src=p?(d.imageView==='frontArtwork'?p.frontArtwork.image:p.image):P.images.find(i=>i.id===d.imageId).image;return `<article><div><h3>${pwe(d.need)}</h3><p>${pwe(d.use)}</p></div><div><img src="${pwe(src)}" alt="${pwe(d.shot)}"><strong>${pwe(d.shot)}</strong></div><div><p>${pwe(d.why)} ${pwe(d.frame)}</p><small>${pwe(d.angle)}</small></div></article>`;}).join('')}</div>`,'pw-choose'));
s.push(pwSlide('framing','Composition / alternate captures',pwHead('Build for the placement','Leave space on purpose.')+`<div class="pw-crop-grid"><div><div class="pw-crop-wide">${pwImage('yellow-overhead')}<span class="pw-clear-zone">Copy area<br><strong>Start with ⅓</strong></span></div><small>Landscape / compose the message side first</small></div><div><div class="pw-crop-portrait">${pwImage('yellow-overhead')}</div><small>4:5 / food crop</small></div><div class="pw-crop-vertical"><span>9:16</span><p>Capture a dedicated vertical.<br>Leave room for the channel’s UI.</p></div></div>`+pwRules(P.framing),'pw-framing'));
s.push(pwSlide('design','Photography in the wider system',pwHead('Photo + type + small graphic accents','Give each element a clear role.')+`<div class="pw-design-grid"><div class="pw-web-example"><div class="pw-example-nav"><img src="assets/logo.png" alt="COOKT"><span>Meals &nbsp; Our story</span></div><div class="pw-web-hero">${pwImage('yellow-overhead')}<h3>${photoTagline().replace(' take ','<br>take<br>')}.</h3></div><div class="pw-example-label">Campaign / a quiet field carries type</div></div><div class="pw-social-example">${pwImage('place-setting')}<div><img src="assets/logo.png" alt="COOKT"><span>${photoTagline().replace(' on frozen','<br>on frozen')}.</span></div><div class="pw-example-label">CRM / image and message in separate blocks</div></div></div><div class="pw-caption-row"><p>Photography carries appetite and lived experience. Type carries the message. Keep iconography and illustration in margins, labels or companion panels, with room around the food.</p><span>Layout studies / not finished applications</span></div>`,'pw-design'));
s.push(pwSlide('shoot','Shoot essentials / coverage',pwHead('A useful library starts on set','Capture the family, not just the hero.')+`<div class="pw-capture-list">${P.capture.map(x=>`<div><span>${x.code}</span><h3>${pwe(x.title)}</h3><p>${pwe(x.deliver)}</p><small>${pwe(x.purpose)}</small></div>`).join('')}</div><div class="pw-shoot-strip">${pwImage('yellow-overhead')}${pwImage('place-setting')}${pwImage('shared-table')}${pwImage('detail')}</div>`,'pw-shoot'));
s.push(pwSlide('delivery','Shoot essentials / quality',pwHead('From brief to delivery','Keep the standard visible.')+pwRules(P.delivery)+`<div class="pw-acceptance"><h3>Every selected image must pass.</h3><ol>${P.acceptance.map(x=>`<li>${pwe(x)}</li>`).join('')}</ol></div><p class="pw-note">${pwe(P.assetPolicy)}</p>`,'pw-delivery'));
if(window.COOKT_PHOTO_REFS)s.push(pwSlide('sources','Reference and asset notes',pwHead('Sources','A curated visual foundation.')+`<div class="pw-credits-grid">${window.COOKT_PHOTO_REFS.map(r=>`<a href="${pwe(r.pin)}"><img src="${pwe(r.image)}" alt="${pwe(r.alt)}"><span>${r.id.replace('ref-','R')} / ${r.board}</span></a>`).join('')}</div><div class="pw-source-copy"><p>Reference images come from the saved pins on the <a href="https://www.pinterest.com/juliacompton/cookt/">cookt</a>, <a href="https://www.pinterest.com/juliacompton/ckt2/">ckt2</a> and <a href="https://www.pinterest.com/juliacompton/ckt/">ckt</a> boards. Pinterest’s recommended products and suggested ideas are excluded. Original creators retain their rights; pin links are provided for source tracing.</p><p>Four new COOKT scenes and one retained close detail are AI-generated direction studies. The existing dish references keep their recorded status. Confirm product accuracy, set samples, hand-talent permissions and usage before production.</p></div>`,'pw-sources'));
return `<article class="photo-guide" data-photo-view="${pwe(view)}"><div class="pw-toolbar"><span>Photography world / ${pwe(P.version)} / ${pwe(P.status)}</span>${P.pdf?`<a href="${pwe(P.pdf)}" target="_blank" rel="noopener">PDF presentation ↗</a>`:'<a href="photography-guide.html" target="_blank" rel="noopener">Open full page ↗</a>'}</div><nav class="pw-jumps" aria-label="Photography page sections">${P.navigation.map(n=>`<a href="#/brand/photography/${n.id}" data-photo-jump="${n.id}">${pwe(n.title)}</a>`).join('')}</nav>${s.join('')}<p class="pw-endnote">${pwe(P.scope)}</p>${typeof renderPlateLibrary==='function'?renderPlateLibrary():''}</article>`;
}
function bindPhotographyGuide(){const g=document.querySelector('.photo-guide');if(!g)return;if(typeof bindPlateLibrary==='function')bindPlateLibrary();g.querySelectorAll('.pw-slide').forEach((s,i)=>s.querySelector('.pw-page-number').textContent=String(i+1).padStart(2,'0'));g.querySelectorAll('[data-photo-jump]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.replaceState({},'',a.getAttribute('href'));const id=a.dataset.photoJump;document.querySelector('#photo-'+id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}));const view=g.dataset.photoView;const id=view==='styling'?'food':view;if(!['pov','all'].includes(id))requestAnimationFrame(()=>document.querySelector('#photo-'+id)?.scrollIntoView({block:'start'}));}
