(()=>{'use strict';const D=window.STUDY_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const options=[{id:1,pack:'lexend',comms:'lexend',packName:'Lexend Bold',headline:'Lexend Bold',body:'Open / NB shown',label:'Lexend + Lexend'},{id:2,pack:'nb',comms:'lexend',packName:'NB International Bold',headline:'Lexend Bold',body:'NB International Regular',label:'NB + Lexend'},{id:3,pack:'nb',comms:'nb',packName:'NB International Bold',headline:'NB International Bold',body:'Open / NB shown',label:'NB + NB'}];
let count=0;const state={compare:'rasta',board:2,specimen:2,format:'retail',treatment:'photo',ink:'base'};
function unique(svg){const id='instance-'+(++count)+'-';return svg.replace(/\bid="([^"]+)"/g,(_,v)=>'id="'+id+v+'"').replace(/url\(#([^)]+)\)/g,(_,v)=>'url(#'+id+v+')').replace(/\bhref="#([^"]+)"/g,(_,v)=>'href="#'+id+v+'"')}
function pack(sku,font='nb',format='retail',treatment='photo',ink='base'){
 let item=D.packs[sku][format+'-'+(format==='retail'?'photo':treatment)+'-'+font];
 if(sku==='rasta'&&font==='nb'&&(format==='retail'||treatment==='photo')&&ink!=='base')item=D.inkPacks[ink];
 return '<img src="'+item.src+'" width="'+item.width+'" height="'+item.height+'" alt="'+D.products.find(p=>p.id===sku).name+' / '+item.font+'" data-source-pdf="'+item.pdf+'">';
}
function logo(){return unique(D.logo)}
function switchButtons(where){return options.map(o=>'<button data-option="'+o.id+'" data-target="'+where+'" aria-pressed="'+(state[where]===o.id)+'">'+'<span>'+String(o.id).padStart(2,'0')+'</span><span>'+o.label+'</span></button>').join('')}
function comparison(){const p=D.products.find(p=>p.id===state.compare);$('#comparison-columns').innerHTML=options.map(o=>`<article class="comparison-col"><div class="option-top"><span class="option-num">0${o.id}</span><h2 class="option-heading">${o.label}</h2></div><div class="pack-svg comparison-pack">${pack(p.id,o.pack)}</div><div class="comparison-pair-label"><span>On pack</span><span>${o.packName}</span></div><div class="comparison-comm"><div class="exact-logo">${logo()}</div><h2 class="font-${o.comms}">A fresh take<br>on frozen.</h2><p>Tastes like someone COOKT it.<br>Because someone did.</p><span class="cta">View meals<span>↗</span></span></div><dl class="type-map"><div><dt>Dish name</dt><dd>${o.packName}</dd></div><div><dt>Headline</dt><dd>${o.headline}</dd></div><div><dt>Body</dt><dd class="${o.id===2?'':'open'}">${o.body}</dd></div></dl></article>`).join('')}
function board(){const o=options[state.board-1];$('#board-retail').innerHTML=pack('rasta',o.pack);$('#board-dtc-pair').innerHTML='<div class="pack-svg">'+pack('blackened',o.pack,'dtc','photo')+'</div><div class="pack-svg">'+pack('blackened',o.pack,'dtc','type')+'</div>';$('#board-pack-font').textContent=o.packName;$('#board-headline').className='font-'+o.comms;$('#board-letters').className='board-letters font-'+o.comms;$('#board-type-name').textContent=o.headline;$('#board-body-name').textContent=o.id===2?'Body / NB Regular':'Body / open';$('#board-summary').textContent='Option 0'+o.id+' / Pack: '+o.packName+' · Headline: '+o.headline;$('.option-switch[data-for="board"]').innerHTML=switchButtons('board')}
function specimens(){const o=options[state.specimen-1];const inkAvailable=o.pack==='nb'&&(state.format==='retail'||state.treatment==='photo');if(!inkAvailable)state.ink='base';$$('[data-ink]').forEach(b=>{b.disabled=!inkAvailable&&b.dataset.ink!=='base';b.title=b.disabled?'This combined color/type variation has not been supplied.':''});$('#specimen-grid').innerHTML=D.products.map((p,i)=>`<figure class="specimen-figure"><button data-inspect="${p.id}" aria-label="Inspect ${p.name}"><div class="pack-svg">${pack(p.id,o.pack,state.format,state.treatment,state.ink)}</div></button><figcaption><span>${p.name}</span><span>${D.heat[p.id]?D.heat[p.id]+' / 3':'No heat'} ↗</span></figcaption></figure>`).join('');$('#specimen-headline').className='font-'+o.comms;$('#spec-pack-font').textContent=o.packName;$('#spec-head-font').textContent=o.headline;$('#spec-body-font').textContent=o.body;$('.option-switch[data-for="specimen"]').innerHTML=switchButtons('specimen');$('#photo-controls').hidden=state.format!=='dtc';$$('[data-format]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.format===state.format)));$$('[data-treatment]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.treatment===state.treatment)));$$('[data-ink]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ink===state.ink)))}
function inspect(id){const p=D.products.find(p=>p.id===id),o=options[state.specimen-1];$('#artwork-title').textContent=p.name;$('#artwork-meta').textContent=(state.format==='retail'?'Retail':'DTC / '+(state.treatment==='photo'?'with food':'without food'))+' · '+o.packName;$('#artwork-large').innerHTML=pack(id,o.pack,state.format,state.treatment,state.ink);const img=$('#artwork-large img');$('#artwork-source').href=img.dataset.sourcePdf;$('#artwork-dialog').showModal()}
$('#compare-product').addEventListener('change',e=>{state.compare=e.target.value;comparison()});$('#reset-specimen').addEventListener('click',()=>{Object.assign(state,{specimen:2,format:'retail',treatment:'photo',ink:'base'});specimens()});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.option){state[b.dataset.target]=+b.dataset.option;b.dataset.target==='board'?board():specimens()}if(b.dataset.format){state.format=b.dataset.format;specimens()}if(b.dataset.treatment){state.treatment=b.dataset.treatment;specimens()}if(b.dataset.ink){state.ink=b.dataset.ink;specimens()}if(b.dataset.inspect)inspect(b.dataset.inspect);if(b.hasAttribute('data-open-sources'))$('#sources-dialog').showModal();if(b.hasAttribute('data-close'))b.closest('dialog').close()});$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$$('[data-logo]').forEach(el=>el.innerHTML=logo());comparison();board();specimens();const io=new IntersectionObserver(es=>{for(const e of es)if(e.isIntersecting){$$('.shell nav a').forEach(a=>a.removeAttribute('aria-current'));$('.shell nav a[href="#'+e.target.id+'"]').setAttribute('aria-current','location')}},{rootMargin:'-15% 0px -60% 0px'});$$('.study').forEach(s=>io.observe(s));const plate=new URLSearchParams(location.search).get('plate');if(['comparison','gestalt','specimens'].includes(plate)){document.body.classList.add('export-plate');document.body.dataset.plate=plate;$$('.study').forEach(s=>s.hidden=s.id!==plate)}window.COOKT_STUDY={state,options,render:()=>{comparison();board();specimens()}};
})();
